name: ai_reliability_medical
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - numpy
  - pandas
  - scipy
  - scikit-learn
  - matplotlib
  - seaborn
  - joblib
  - tqdm
  - pip
  - pytorch
  - torchvision
  - torchaudio
  - cpuonly
  - pip:
      - xgboost